### ISSUE TITLE
Potential import collision: import path should be "github.com/nsqio/go-nsq", not "github.com/bitly/go-nsq"

### ISSUE THREAD

**Issue by KateGo520** [tomatool/tomato#114]
## Background
I find that `github.com/nsqio/go-nsq` and `github.com/bitly/go-nsq` coexist in this repo：
https://github.com/tomatool/tomato/blob/main/go.mod （Line 9&22）
```
github.com/bitly/go-nsq v1.0.7
github.com/nsqio/go-nsq v1.0.7 // indirect
```
That’s because the "github.com/bitly/go-nsq" has already been redirected to "github.com/nsqio/go-nsq". When you use the old path "github.com/bitly/go-nsq" to import the `go-nsq`, github automatically directed to `github.com/nsqio/go-nsq`, returned the repo `github.com/nsqio/go-nsq`, and reintroduces `github.com/nsqio/go-nsq` through the import statements "import github.com/nsqio/go-nsq" in the go source file of `nsqio/go-nsq`.

https://github.com/nsqio/go-nsq/blob/v1.0.7/config_flag_test.go
```
package nsq_test
import (
	"flag"
	"github.com/nsqio/go-nsq"
)
```
This will work in isolation, bring about potential risks and problems.

## Solution
Replace all the old import paths, change `"github.com/bitly/go-nsq"` to `"github.com/nsqio/go-nsq"`.
Where did you import it: https://github.com/tomatool/tomato/search?q=github.com%2Fbitly%2Fgo-nsq&unscoped_q=github.com%2Fbitly%2Fgo-nsq

**Comment by KateGo520** [comment]
@alileza  Could you help me review this issue? Thx :p

**Comment by alileza** [comment]
@KateGo520 nice catch! since the nsqio dependency is indirect dependency of bitly module, I think this won't cause any trouble. But either way, I think it's nice to clean up since bitly/go-nsq repo is not existed anymore. so I just submitted a PR to cleanup vendor. If you can 👀and approve the PR would be great ✌🏻

**Comment by KateGo520** [comment]
@alileza I've approved it. Thank you for your contribution!
