### ISSUE TITLE
Enable creating fully defined stubs via JSON with wiremock resource

### ISSUE THREAD

**Issue by martroosaare** [tomatool/tomato#90]
**Is your feature request related to a problem? Please describe.**
I would like to use wiremock to check for request body patterns and provide an XML response body defined in a file.

At the moment, wiremock has a rigid setup only allowing request counting (no matching possible) and only inline JSON body. Wiremock itself provides many options via its JSON api (http://wiremock.org/docs/stubbing/) which are also easy to use and have powerful documentation. I see no reason to limit it for Tomato users.

**Describe the solution you'd like**
I would like to be able to define, in my feature file, the JSON that would define the whole mapping for wiremock, like this:
```{
    "request": {
        "method": "GET",
        "url": "/some/thing"
    },
    "response": {
        "status": 200,
        "body": "Hello world!",
        "headers": {
            "Content-Type": "text/plain"
        }
    }
}
```

**Describe alternatives you've considered**
I considered building tests in pure Go and using wiremock separately, but I like how Tomato integrates with rabbitmq and I would like to keep using it. I also tried setting up mappings for wiremock separately, by putting JSON files in mapping directory, but as Tomato resets wiremock after each scenario, this did not work out.

**Additional context**
I think one possible solution would be to add an additional step for wiremock, something along the lines of `Given wiremock with JSON mapping` or similar. Then, this whole JSON is POSTed to wiremock JSON api.

I think this addition would be very powerful for users who use Tomato with wiremock as this would enable full stubbing features of wiremock and require little coding in the Tomato itself, as wiremock has stubbing nicely built in already.

**Comment by alileza** [comment]
Hi @martroosaare, I like the idea of extending the wiremock feature to add more flexibility to resource usage. 

But adding this feature would require us to change an `http/server` interface to have resource specific _(wiremock)_ method, which kind of kills the abstraction idea. 

I'm suggesting to reword the **action** to be more generic, like
```gherkin
Given "some-api" set configuration for "stub" to
``
    "request": {
        "method": "GET",
        "url": "/some/thing"
    },
    "response": {
        "status": 200,
        "body": "Hello world!",
        "headers": {
            "Content-Type": "text/plain"
        }
    }
}
``
```

That way, that action can applied to any `http/server` implementation, and we can easily add new `wiremock` feature without changing the interface.

What do you think of that idea? I'm open for any ideas to have this.

@snagles some thought?

**Comment by martroosaare** [comment]
Yesd, this sounds good. Also, from the user perspective, I find JSON as clear as specifying the method/response code/other parameters in Gherkin (and less prone to mistakes as Gherkin is very strict about wording, needing exact matches)
